all :
	echo "précisez classes ou clear"

clear :
	rm build/*.class

classes :
	javac -cp src/ -d build/ src/*

test :
	java -cp build/ TestExpression

#classes :
#	javac Expression.java
#	javac OperationBinaire.java
#	javac Addition.java
#	javac Constante.java
#	javac Cos.java
#	javac Division.java
#	javac Exp.java
#	javac Log.java
#	javac Multiplication.java
#	javac OperationUnaire.java
#	javac Sin.java
#	javac Soustraction.java
#	javac Variable.java

#clear :
#	rm build/*
