# ceci est un commentaire

jeu : jeu.c 
	gcc -Wall jeu.c -o jeu

pgcd : pgcd.c
	gcc -Wall pgcd.c -o pgcd

pgcd_pts : pgcd.c
	gcc -Wall -D MISEAUPOINT pgcd.c -o pgcd_pts

test_math_lib : math_lib.c math_lib.h
	gcc -Wall math_lib.c math_lib.h -D LIBRAIRY pgcd.c -o test_math_lib



