all :
	echo ""

clean :
	rm *.class

bibliotheque : Bibliotheque.java
	javac $<

document : Document.java
	javac $<

livre : Livre.java
	javac $<

manuel : Manuel.java
	javac $<

revue : Revue.java
	javac $<

roman : Roman.java
	javac $<
