all :
	echo "classes ou clean"

clean :
	rm *.class

classes :
	javac Activite.java
	javac CM.java
	javac Creneau.java
	javac Discipline.java
	javac Groupe.java
	javac Planning.java
	javac Salle.java
	javac SalleCTD.java
	javac SalleTP.java
	javac TD.java
	javac TP.java
